name: 'Append path to environment variable using powershell'
description: 'Permanently append path to a specified environment variable using powershell. The resulting environment variable value will be persistent across all the following job steps.'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  path:
    description: 'path to append'
    required: true
  env-var:
    description: 'environment variable name to append the path to'
    required: false
    default: 'PATH'
runs:
  using: "composite"
  steps:
    - name: append path
      run: echo "${{ inputs.env-var }}=$env:${{ inputs.env-var }};${{ inputs.path }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell
